// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: youtube_channel.
// - Entity ID: 102019c366cf94379fa8bf2a93a26bb3ecb.
// - Entity Version: 102019c3671fd837a1b80e10fef09754638.
// - Task ID: 6986c4fa3615eb895e713122.
// - Task Root ID: 6986c3d360e9598533989dbc.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for YoutubeChannelModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface YoutubeChannelModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  user_id: string;
  channel_id: string;
  channel_name: string;
  access_token: string;
  refresh_token: string;
  connected_at: string;
  last_upload_at?: string | null;
}

/**
 * ORM class for YoutubeChannel entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class YoutubeChannelORM {
  private static instance: YoutubeChannelORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019c366cf94379fa8bf2a93a26bb3ecb';
    this.entityName = 'youtube_channel';
    this.entityVersion = '102019c3671fd837a1b80e10fef09754638';
    this.taskId = '6986c4fa3615eb895e713122';
    this.taskRootId = '6986c3d360e9598533989dbc';
  }

  /**
   * Get singleton instance of YoutubeChannelORM
   */
  public static getInstance(): YoutubeChannelORM {
    if (!YoutubeChannelORM.instance) {
      YoutubeChannelORM.instance = new YoutubeChannelORM();
    }
    
    return YoutubeChannelORM.instance;
  }

  /**
   * Get youtube_channel by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getYoutubeChannelByIDs(ids: string[]): Promise<YoutubeChannelModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete youtube_channel by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteYoutubeChannelByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all YoutubeChannel records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllYoutubeChannel(): Promise<YoutubeChannelModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new YoutubeChannel record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertYoutubeChannel(data: YoutubeChannelModel[]): Promise<YoutubeChannelModel[]> {
    const structured = data.map((item) => CreateData(YoutubeChannelModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all YoutubeChannel records
   */
  async purgeAllYoutubeChannel(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List YoutubeChannel records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listYoutubeChannel(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[YoutubeChannelModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get youtube_channel by Id index
   * This function gets data by index.
   */
  async getYoutubeChannelById(
    id: string,
  ): Promise<YoutubeChannelModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) youtube_channel by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setYoutubeChannelById(
    id: string,
    data: YoutubeChannelModel
  ): Promise<YoutubeChannelModel[]> {
    const index = createIndexId(
      id
    );

    const values = YoutubeChannelModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete youtube_channel by Id index
   */
  async deleteYoutubeChannelById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get youtube_channel by DataCreator index
   * This function gets data by index.
   */
  async getYoutubeChannelByDataCreator(
    data_creator: string,
  ): Promise<YoutubeChannelModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) youtube_channel by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setYoutubeChannelByDataCreator(
    data_creator: string,
    data: YoutubeChannelModel
  ): Promise<YoutubeChannelModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = YoutubeChannelModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete youtube_channel by DataCreator index
   */
  async deleteYoutubeChannelByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get youtube_channel by DataUpdater index
   * This function gets data by index.
   */
  async getYoutubeChannelByDataUpdater(
    data_updater: string,
  ): Promise<YoutubeChannelModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) youtube_channel by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setYoutubeChannelByDataUpdater(
    data_updater: string,
    data: YoutubeChannelModel
  ): Promise<YoutubeChannelModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = YoutubeChannelModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete youtube_channel by DataUpdater index
   */
  async deleteYoutubeChannelByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get youtube_channel by UserId index
   * This function gets data by index.
   */
  async getYoutubeChannelByUserId(
    user_id: string,
  ): Promise<YoutubeChannelModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) youtube_channel by UserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setYoutubeChannelByUserId(
    user_id: string,
    data: YoutubeChannelModel
  ): Promise<YoutubeChannelModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const values = YoutubeChannelModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete youtube_channel by UserId index
   */
  async deleteYoutubeChannelByUserId(
    user_id: string
  ): Promise<void> {
    const index = createIndexUserId(
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get youtube_channel by ChannelId index
   * This function gets data by index.
   */
  async getYoutubeChannelByChannelId(
    channel_id: string,
  ): Promise<YoutubeChannelModel[]> {
    const index = createIndexChannelId(
      channel_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) youtube_channel by ChannelId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setYoutubeChannelByChannelId(
    channel_id: string,
    data: YoutubeChannelModel
  ): Promise<YoutubeChannelModel[]> {
    const index = createIndexChannelId(
      channel_id
    );

    const values = YoutubeChannelModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete youtube_channel by ChannelId index
   */
  async deleteYoutubeChannelByChannelId(
    channel_id: string
  ): Promise<void> {
    const index = createIndexChannelId(
      channel_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to YoutubeChannelModel data array
   */
  private resultToData(values: Data[]): YoutubeChannelModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return YoutubeChannelModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as YoutubeChannelModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized YoutubeChannelModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is YoutubeChannelModel => item !== null);
  }
}

/**
 * Convert YoutubeChannelModel data to Value array
 */
function YoutubeChannelModelToValues(data: YoutubeChannelModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'channel_id', type: DataType.string, defaultValue: '' },
    { key: 'channel_name', type: DataType.string, defaultValue: '' },
    { key: 'access_token', type: DataType.string, defaultValue: '' },
    { key: 'refresh_token', type: DataType.string, defaultValue: '' },
    { key: 'connected_at', type: DataType.string, defaultValue: '' },
    { key: 'last_upload_at', type: DataType.string, defaultValue: null },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof YoutubeChannelModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to YoutubeChannelModel data
 */
function YoutubeChannelModelFromValues(values: Value[]): YoutubeChannelModel {
  const data: Partial<YoutubeChannelModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'channel_id':
        data.channel_id = ParseValue(value, DataType.string) as string;
        break;
      case 'channel_name':
        data.channel_name = ParseValue(value, DataType.string) as string;
        break;
      case 'access_token':
        data.access_token = ParseValue(value, DataType.string) as string;
        break;
      case 'refresh_token':
        data.refresh_token = ParseValue(value, DataType.string) as string;
        break;
      case 'connected_at':
        data.connected_at = ParseValue(value, DataType.string) as string;
        break;
      case 'last_upload_at':
        data.last_upload_at = ParseValue(value, DataType.string) as string | null;
        break;
    }
  }
  
  return data as YoutubeChannelModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for UserId fields
 */
function createIndexUserId(
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['user_id'],
    values
  };
}
/**
 * Create index for ChannelId fields
 */
function createIndexChannelId(
  channel_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, channel_id, 'channel_id'),
  ];

  return {
    fields: ['channel_id'],
    values
  };
}

export default YoutubeChannelORM;