// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: video_generation.
// - Entity ID: 102019c366cf94377318f14e1f5de894f63.
// - Entity Version: 102019c3671fd837a1b80e10fef09754638.
// - Task ID: 6986c4fa3615eb895e713122.
// - Task Root ID: 6986c3d360e9598533989dbc.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for VideoGenerationStatus
 */
export enum VideoGenerationStatus {
  Unspecified = 0,
  Generating = 1,
  Ready = 2,
  Uploaded = 3,
  Failed = 4,
}



/**
 * Interface for VideoGenerationModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface VideoGenerationModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  user_id: string;
  niche_id: string;
  topic: string;
  script?: string | null;
  status: VideoGenerationStatus;
  video_url?: string | null;
  shorts_url?: string | null;
  thumbnail_url?: string | null;
  youtube_video_id?: string | null;
  youtube_shorts_id?: string | null;
  uploaded_at?: string | null;
}

/**
 * ORM class for VideoGeneration entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class VideoGenerationORM {
  private static instance: VideoGenerationORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019c366cf94377318f14e1f5de894f63';
    this.entityName = 'video_generation';
    this.entityVersion = '102019c3671fd837a1b80e10fef09754638';
    this.taskId = '6986c4fa3615eb895e713122';
    this.taskRootId = '6986c3d360e9598533989dbc';
  }

  /**
   * Get singleton instance of VideoGenerationORM
   */
  public static getInstance(): VideoGenerationORM {
    if (!VideoGenerationORM.instance) {
      VideoGenerationORM.instance = new VideoGenerationORM();
    }
    
    return VideoGenerationORM.instance;
  }

  /**
   * Get video_generation by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getVideoGenerationByIDs(ids: string[]): Promise<VideoGenerationModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete video_generation by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteVideoGenerationByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all VideoGeneration records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllVideoGeneration(): Promise<VideoGenerationModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new VideoGeneration record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertVideoGeneration(data: VideoGenerationModel[]): Promise<VideoGenerationModel[]> {
    const structured = data.map((item) => CreateData(VideoGenerationModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all VideoGeneration records
   */
  async purgeAllVideoGeneration(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List VideoGeneration records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listVideoGeneration(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[VideoGenerationModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get video_generation by Id index
   * This function gets data by index.
   */
  async getVideoGenerationById(
    id: string,
  ): Promise<VideoGenerationModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) video_generation by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setVideoGenerationById(
    id: string,
    data: VideoGenerationModel
  ): Promise<VideoGenerationModel[]> {
    const index = createIndexId(
      id
    );

    const values = VideoGenerationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete video_generation by Id index
   */
  async deleteVideoGenerationById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get video_generation by DataCreator index
   * This function gets data by index.
   */
  async getVideoGenerationByDataCreator(
    data_creator: string,
  ): Promise<VideoGenerationModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) video_generation by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setVideoGenerationByDataCreator(
    data_creator: string,
    data: VideoGenerationModel
  ): Promise<VideoGenerationModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = VideoGenerationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete video_generation by DataCreator index
   */
  async deleteVideoGenerationByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get video_generation by DataUpdater index
   * This function gets data by index.
   */
  async getVideoGenerationByDataUpdater(
    data_updater: string,
  ): Promise<VideoGenerationModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) video_generation by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setVideoGenerationByDataUpdater(
    data_updater: string,
    data: VideoGenerationModel
  ): Promise<VideoGenerationModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = VideoGenerationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete video_generation by DataUpdater index
   */
  async deleteVideoGenerationByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get video_generation by UserId index
   * This function gets data by index.
   */
  async getVideoGenerationByUserId(
    user_id: string,
  ): Promise<VideoGenerationModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) video_generation by UserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setVideoGenerationByUserId(
    user_id: string,
    data: VideoGenerationModel
  ): Promise<VideoGenerationModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const values = VideoGenerationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete video_generation by UserId index
   */
  async deleteVideoGenerationByUserId(
    user_id: string
  ): Promise<void> {
    const index = createIndexUserId(
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get video_generation by NicheId index
   * This function gets data by index.
   */
  async getVideoGenerationByNicheId(
    niche_id: string,
  ): Promise<VideoGenerationModel[]> {
    const index = createIndexNicheId(
      niche_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) video_generation by NicheId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setVideoGenerationByNicheId(
    niche_id: string,
    data: VideoGenerationModel
  ): Promise<VideoGenerationModel[]> {
    const index = createIndexNicheId(
      niche_id
    );

    const values = VideoGenerationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete video_generation by NicheId index
   */
  async deleteVideoGenerationByNicheId(
    niche_id: string
  ): Promise<void> {
    const index = createIndexNicheId(
      niche_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get video_generation by Status index
   * This function gets data by index.
   */
  async getVideoGenerationByStatus(
    status: VideoGenerationStatus,
  ): Promise<VideoGenerationModel[]> {
    const index = createIndexStatus(
      status
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) video_generation by Status index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setVideoGenerationByStatus(
    status: VideoGenerationStatus,
    data: VideoGenerationModel
  ): Promise<VideoGenerationModel[]> {
    const index = createIndexStatus(
      status
    );

    const values = VideoGenerationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete video_generation by Status index
   */
  async deleteVideoGenerationByStatus(
    status: VideoGenerationStatus
  ): Promise<void> {
    const index = createIndexStatus(
      status
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get video_generation by YoutubeVideoId index
   * This function gets data by index.
   */
  async getVideoGenerationByYoutubeVideoId(
    youtube_video_id: string,
  ): Promise<VideoGenerationModel[]> {
    const index = createIndexYoutubeVideoId(
      youtube_video_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) video_generation by YoutubeVideoId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setVideoGenerationByYoutubeVideoId(
    youtube_video_id: string,
    data: VideoGenerationModel
  ): Promise<VideoGenerationModel[]> {
    const index = createIndexYoutubeVideoId(
      youtube_video_id
    );

    const values = VideoGenerationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete video_generation by YoutubeVideoId index
   */
  async deleteVideoGenerationByYoutubeVideoId(
    youtube_video_id: string
  ): Promise<void> {
    const index = createIndexYoutubeVideoId(
      youtube_video_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get video_generation by YoutubeShortsId index
   * This function gets data by index.
   */
  async getVideoGenerationByYoutubeShortsId(
    youtube_shorts_id: string,
  ): Promise<VideoGenerationModel[]> {
    const index = createIndexYoutubeShortsId(
      youtube_shorts_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) video_generation by YoutubeShortsId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setVideoGenerationByYoutubeShortsId(
    youtube_shorts_id: string,
    data: VideoGenerationModel
  ): Promise<VideoGenerationModel[]> {
    const index = createIndexYoutubeShortsId(
      youtube_shorts_id
    );

    const values = VideoGenerationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete video_generation by YoutubeShortsId index
   */
  async deleteVideoGenerationByYoutubeShortsId(
    youtube_shorts_id: string
  ): Promise<void> {
    const index = createIndexYoutubeShortsId(
      youtube_shorts_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to VideoGenerationModel data array
   */
  private resultToData(values: Data[]): VideoGenerationModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return VideoGenerationModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as VideoGenerationModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized VideoGenerationModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is VideoGenerationModel => item !== null);
  }
}

/**
 * Convert VideoGenerationModel data to Value array
 */
function VideoGenerationModelToValues(data: VideoGenerationModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'niche_id', type: DataType.string, defaultValue: '' },
    { key: 'topic', type: DataType.string, defaultValue: '' },
    { key: 'script', type: DataType.string, defaultValue: null },
    { key: 'status', type: DataType.enumeration, defaultValue: 0 },
    { key: 'video_url', type: DataType.string, defaultValue: null },
    { key: 'shorts_url', type: DataType.string, defaultValue: null },
    { key: 'thumbnail_url', type: DataType.string, defaultValue: null },
    { key: 'youtube_video_id', type: DataType.string, defaultValue: null },
    { key: 'youtube_shorts_id', type: DataType.string, defaultValue: null },
    { key: 'uploaded_at', type: DataType.string, defaultValue: null },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof VideoGenerationModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to VideoGenerationModel data
 */
function VideoGenerationModelFromValues(values: Value[]): VideoGenerationModel {
  const data: Partial<VideoGenerationModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'niche_id':
        data.niche_id = ParseValue(value, DataType.string) as string;
        break;
      case 'topic':
        data.topic = ParseValue(value, DataType.string) as string;
        break;
      case 'script':
        data.script = ParseValue(value, DataType.string) as string | null;
        break;
      case 'status':
        data.status = ParseValue(value, DataType.enumeration) as VideoGenerationStatus;
        break;
      case 'video_url':
        data.video_url = ParseValue(value, DataType.string) as string | null;
        break;
      case 'shorts_url':
        data.shorts_url = ParseValue(value, DataType.string) as string | null;
        break;
      case 'thumbnail_url':
        data.thumbnail_url = ParseValue(value, DataType.string) as string | null;
        break;
      case 'youtube_video_id':
        data.youtube_video_id = ParseValue(value, DataType.string) as string | null;
        break;
      case 'youtube_shorts_id':
        data.youtube_shorts_id = ParseValue(value, DataType.string) as string | null;
        break;
      case 'uploaded_at':
        data.uploaded_at = ParseValue(value, DataType.string) as string | null;
        break;
    }
  }
  
  return data as VideoGenerationModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for UserId fields
 */
function createIndexUserId(
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['user_id'],
    values
  };
}
/**
 * Create index for NicheId fields
 */
function createIndexNicheId(
  niche_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, niche_id, 'niche_id'),
  ];

  return {
    fields: ['niche_id'],
    values
  };
}
/**
 * Create index for Status fields
 */
function createIndexStatus(
  status: VideoGenerationStatus
): Index {
  const values: Value[] = [
    CreateValue(DataType.enumeration, status, 'status'),
  ];

  return {
    fields: ['status'],
    values
  };
}
/**
 * Create index for YoutubeVideoId fields
 */
function createIndexYoutubeVideoId(
  youtube_video_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, youtube_video_id, 'youtube_video_id'),
  ];

  return {
    fields: ['youtube_video_id'],
    values
  };
}
/**
 * Create index for YoutubeShortsId fields
 */
function createIndexYoutubeShortsId(
  youtube_shorts_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, youtube_shorts_id, 'youtube_shorts_id'),
  ];

  return {
    fields: ['youtube_shorts_id'],
    values
  };
}

export default VideoGenerationORM;