// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { PostOfficialApiPresignS3UploadData, PostOfficialApiPresignS3UploadErrors, PostOfficialApiPresignS3UploadResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Generate presigned URL for S3 upload
 *
 * Creates a presigned URL that allows direct upload to S3 bucket.
 * After getting the presigned URL, you must make a separate PUT request to that URL with the file content to complete the upload.
 */
export const postOfficialApiPresignS3Upload = <ThrowOnError extends boolean = false>(options: Options<PostOfficialApiPresignS3UploadData, ThrowOnError>) => (options.client ?? client).post<PostOfficialApiPresignS3UploadResponses, PostOfficialApiPresignS3UploadErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/official-api/presign-s3-upload',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
